import Link from "next/link";
import { Activity, ArrowRight, Boxes, CheckCircle2, CircleDollarSign, Clock3, Server, ShieldAlert, UsersRound, WalletCards } from "lucide-react";
import { CloudShell } from "@/components/CloudShell";

const signals=[
 {label:"Cash position",value:"RM482,300",note:"Healthy · +8.4%",icon:WalletCards,tone:"green"},
 {label:"Workforce",value:"128",note:"113 present today",icon:UsersRound,tone:"blue"},
 {label:"Cloud uptime",value:"99.98%",note:"10 of 12 apps online",icon:Activity,tone:"violet"},
 {label:"Open approvals",value:"14",note:"3 high-value items",icon:Clock3,tone:"amber"},
];
export default function Home(){return <CloudShell title="Executive Overview" eyebrow="PREMIER CLOUD · COMPANY OPERATIONS OS" action={<Link className="primary-action" href="/approvals">Review approvals <ArrowRight size={13}/></Link>}>
 <section className="os-hero"><div><span className="os-kicker"><i/> LIVE COMPANY PULSE</span><h2>Good morning, Amir.</h2><p>Your people, finances and infrastructure are operating normally. Fourteen decisions need attention.</p></div><div className="os-period">FRIDAY · 14 AUGUST 2026 <b>Kuala Lumpur · 09:42 MYT</b></div></section>
 <section className="os-metrics">{signals.map(s=><article key={s.label}><div className={`os-icon ${s.tone}`}><s.icon/></div><span>{s.label}</span><strong>{s.value}</strong><small className={s.tone}>{s.note}</small></article>)}</section>
 <section className="os-split"><article className="os-panel"><header><div><small>ACTION CENTRE</small><h3>Decisions awaiting leadership</h3></div><Link className="text-action" href="/approvals">View all →</Link></header><div className="request-list"><Link href="/approvals"><div className="request-icon payroll"><CircleDollarSign/></div><span><small>PAYROLL · PAY-0826</small><b>August payroll · 128 employees</b><em>HR approved · Finance action required</em></span><strong>RM63,400</strong><ArrowRight/></Link><Link href="/approvals"><div className="request-icon"><Boxes/></div><span><small>PURCHASE · PR-2026-0042</small><b>14 laptops for Operations</b><em>Finance Manager approved · CFO action required</em></span><strong>RM14,500</strong><ArrowRight/></Link><Link href="/approvals"><div className="request-icon"><ShieldAlert/></div><span><small>SECURITY · SEC-2026-019</small><b>CRM certificate expires in 8 days</b><em>Infrastructure action required</em></span><strong>High</strong><ArrowRight/></Link></div></article>
 <article className="os-panel"><header><div><small>CONNECTED OPERATIONS</small><h3>Company health</h3></div><span className="os-pill green">All systems normal</span></header><div className="health-stack"><Link href="/hr"><UsersRound/><span><b>HR & People</b><small>4 leave · 6 overtime · payroll preparing</small></span><CheckCircle2/></Link><Link href="/accounts"><WalletCards/><span><b>Accounts</b><small>7 invoices · 3 expenses · 2 purchase orders</small></span><CheckCircle2/></Link><Link href="/applications"><Server/><span><b>Cloud Operations</b><small>10 running · 2 offline · 74% storage</small></span><ShieldAlert/></Link></div></article></section>
 <section className="os-panel"><header><div><small>AI OPERATIONS BRIEF</small><h3>What deserves attention today</h3></div><span className="os-pill violet">3 insights</span></header><div className="insight-grid"><div><i>01</i><span><b>Payroll is ready for Finance</b><small>All 128 employee records passed validation. Four manual exceptions were resolved by HR.</small></span></div><div><i>02</i><span><b>Storage will reach 80% in 19 days</b><small>Backups are the fastest-growing category. Review retention before adding capacity.</small></span></div><div><i>03</i><span><b>Receivables concentration increased</b><small>Two customers represent 41% of RM76,300 outstanding. Follow-up is recommended.</small></span></div></div></section>
 </CloudShell>}
