"use client";
import { useMemo, useState } from "react";
import { Check, ChevronRight, CircleDollarSign, GitPullRequestArrow, Info, LockKeyhole, MessageSquareMore, ShieldCheck, X } from "lucide-react";
import { CloudShell } from "@/components/CloudShell";
import { approvalQueue, policies } from "@/lib/company-data";
import { resolveApprovalPath } from "@/lib/approval-engine";

export default function ApprovalsPage(){
 const [filter,setFilter]=useState("All"); const [selected,setSelected]=useState(approvalQueue[0]); const [states,setStates]=useState<Record<string,string>>({}); const [modal,setModal]=useState<"approve"|"reject"|"info"|null>(null); const [settings,setSettings]=useState(false); const [toast,setToast]=useState("");
 const queue=useMemo(()=>filter==="All"?approvalQueue:approvalQueue.filter(x=>x.type===filter),[filter]);
 const finish=()=>{if(!modal)return; const label=modal==="approve"?"Approved":modal==="reject"?"Rejected":"More information requested";setStates(s=>({...s,[selected.id]:label}));setModal(null);setToast(`${selected.id} · ${label}`);setTimeout(()=>setToast(""),2400)};
 const path=selected.numericAmount?resolveApprovalPath(selected.numericAmount):["Manager","HR"];
 return <CloudShell title="Approval Engine" eyebrow="COMPANY OS · GOVERNANCE" action={<button className="secondary-action" onClick={()=>setSettings(true)}><GitPullRequestArrow size={14}/> Workflow settings</button>}>
  <section className="os-hero approvals-hero"><div><span className="os-kicker"><i/> SHARED APPROVAL ENGINE</span><h2>One queue. Clear authority.</h2><p>Every decision across HR, finance and operations follows policy and leaves an audit trail.</p></div><div className="approval-summary"><span><b>14</b> awaiting you</span><span><b>3</b> high value</span><span><b>2.1h</b> average response</span></div></section>
  <section className="approval-layout"><article className="os-panel queue-panel"><header><div><small>YOUR QUEUE</small><h3>Requests needing action</h3></div></header><div className="filter-tabs">{["All","Payroll","Purchase","Expense","Overtime","Leave"].map(f=><button className={filter===f?"on":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><div className="request-list">{queue.map(r=><button onClick={()=>setSelected(r)} className={selected.id===r.id?"selected":""} key={r.id}><div className={`request-icon ${r.type.toLowerCase()}`}>{r.type==="Payroll"?<CircleDollarSign/>:<GitPullRequestArrow/>}</div><span><small>{r.type.toUpperCase()} · {r.id}</small><b>{r.title}</b><em>{r.owner}</em></span><strong>{r.amount}</strong><ChevronRight/></button>)}</div></article>
  <article className="os-panel approval-detail"><header><div><small>{selected.type.toUpperCase()} · {selected.id}</small><h3>{selected.title}</h3></div><span className="os-pill amber">{states[selected.id]||selected.status}</span></header><div className="detail-amount"><span>REQUEST VALUE</span><b>{selected.amount}</b><small>Submitted by {selected.owner}</small></div><div className="risk-check"><ShieldCheck/><span><b>{selected.risk}</b><small>Automated policy and duplicate checks complete</small></span></div><h4>Approval route</h4><div className="route-line">{path.map((p,i)=><div className={i<selected.step?"done":i===selected.step?"active":""} key={p}><i>{i<selected.step?<Check/>:i+1}</i><span><b>{p}</b><small>{i<selected.step?"Approved":i===selected.step?"Your action":"Waiting"}</small></span>{i<path.length-1&&<ChevronRight/>}</div>)}</div><h4>Audit trail</h4><div className="audit-list"><p><i/><span><b>Request submitted</b><small>13 Aug 2026, 3:48 PM · {selected.owner}</small></span></p><p><i/><span><b>Policy route assigned</b><small>Automatic · Amount and request type evaluated</small></span></p><p><i/><span><b>Previous approval recorded</b><small>13 Aug 2026, 4:32 PM · Signed and immutable</small></span></p></div><div className="decision-bar"><button onClick={()=>setModal("reject")}><X/> Reject</button><button onClick={()=>setModal("info")}><MessageSquareMore/> Need info</button><button onClick={()=>setModal("approve")}><Check/> Approve</button></div></article></section>
  <section className="os-panel policy-panel"><header><div><small>ACTIVE FINANCE POLICY</small><h3>Approval thresholds</h3></div><span className="os-pill green">Version 3 · Active</span></header><div className="policy-grid">{policies.map((p,i)=><div key={p.range}><i>{i+1}</i><span><b>{p.range}</b><small>{p.path.join("  →  ")}</small></span></div>)}</div><p className="security-rule"><LockKeyhole size={13}/><span><b>Least privilege enforced:</b> IT and System Admin roles can maintain the platform but cannot view salary, banking or restricted HR records.</span></p></section>
  {modal&&<div className="modal-backdrop"><div className="decision-modal"><div className={`modal-icon ${modal}`} >{modal==="approve"?<Check/>:modal==="reject"?<X/>:<Info/>}</div><h3>{modal==="approve"?"Approve this request?":modal==="reject"?"Reject this request?":"Request more information?"}</h3><p>Your decision will be signed as Amir Rahman and added to the immutable audit trail.</p><textarea placeholder="Add a decision note (optional)"/><div><button onClick={()=>setModal(null)}>Cancel</button><button onClick={finish}>Confirm decision</button></div></div></div>}
  {settings&&<div className="modal-backdrop"><div className="decision-modal settings-modal"><div className="modal-icon info"><GitPullRequestArrow/></div><h3>Workflow settings</h3><p>Approval routes are selected automatically by request value.</p><div className="settings-list">{policies.map(p=><div key={p.range}><b>{p.range}</b><span>{p.path.join(" → ")}</span></div>)}</div><div><button onClick={()=>setSettings(false)}>Close</button><button onClick={()=>{setSettings(false);setToast("Workflow policy saved");setTimeout(()=>setToast(""),2200)}}>Save policy</button></div></div></div>}
  {toast&&<div className="dark-toast">✓ {toast}</div>}
 </CloudShell>
}
