"use client";
import { useState } from "react";
import { CalendarCheck, Clock3, FileCheck2, LockKeyhole, UserPlus, UsersRound } from "lucide-react";
import { CloudShell } from "@/components/CloudShell";
import { ActionDrawer, FormField, StepList } from "@/components/ActionDrawer";
import { hrMetrics } from "@/lib/company-data";
const departments=[{n:"Operations",v:54},{n:"Others",v:33},{n:"Finance",v:17},{n:"IT",v:13},{n:"Management",v:11}];
const people=[["PCG-0118","Siti Aisyah","Finance","Farah Ibrahim","Present","Ready"],["PCG-0092","Daniel Lim","IT","Kumar Raj","Present","Ready"],["PCG-0124","Nur Amalina","Operations","Farid Azman","On leave","Verified"],["PCG-0064","Haziq Roslan","Management","Amir Rahman","Present","Review"]];
export default function HRPage(){
 const [toast,setToast]=useState(""); const [drawer,setDrawer]=useState<"employee"|"payroll"|"profile"|null>(null); const [person,setPerson]=useState(""); const act=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const employee=people.find(p=>p[1]===person);
 return <CloudShell title="HR & People" eyebrow="COMPANY OS · PEOPLE OPERATIONS" action={<button className="primary-action" onClick={()=>setDrawer("employee")}><UserPlus size={14}/> Add employee</button>}>
  <section className="os-hero"><div><span className="os-kicker"><i/> PEOPLE OPERATIONS</span><h2>Your workforce, connected to payroll.</h2><p>Attendance, leave, overtime and payroll move through one governed workflow.</p></div><div className="os-period">AUGUST 2026 <b>Payroll closes in 4 days</b></div></section>
  <section className="os-metrics">{hrMetrics.map((m,i)=><article key={m.label}><div className={`os-icon ${m.tone}`}>{[<UsersRound key="u"/>,<CalendarCheck key="c"/>,<FileCheck2 key="f"/>,<Clock3 key="t"/>][i]}</div><span>{m.label}</span><strong>{m.value}</strong><small className={m.tone}>{m.note}</small></article>)}</section>
  <section className="os-split"><article className="os-panel"><header><div><small>PAYROLL HANDOFF</small><h3>August payroll readiness</h3></div><button className="os-pill amber" onClick={()=>setDrawer("payroll")}>12 actions</button></header><div className="workflow-track">{["Attendance","HR verified","Payroll engine","HR approval","Accounts approval","Payment","Payslips"].map((s,i)=><div className={i<3?"done":i===3?"current":""} key={s}><i>{i<3?"✓":i+1}</i><span>{s}</span></div>)}</div><div className="handoff"><div><span>Employees</span><b>128 / 128</b></div><div><span>Gross payroll</span><b>RM63,400</b></div><div><span>Exceptions</span><b className="amber-text">4 open</b></div><button onClick={()=>setDrawer("payroll")}>Review payroll →</button></div><p className="security-rule"><LockKeyhole size={13}/><span><b>Controlled handoff:</b> HR prepares payroll; Accounts owns payment.</span></p></article>
  <article className="os-panel"><header><div><small>WORKFORCE MIX</small><h3>Employees by department</h3></div><b>128 total</b></header><div className="dept-chart">{departments.map(d=><button onClick={()=>act(`${d.n} employee list filtered`)} key={d.n}><label><span>{d.n}</span><b>{d.v}</b></label><i><b style={{width:`${d.v/54*100}%`}}/></i></button>)}</div></article></section>
  <section className="os-panel os-table-panel"><header><div><small>PEOPLE DIRECTORY</small><h3>Employee records</h3></div><div className="action-summary"><button onClick={()=>act("4 leave requests shown")}><b>4</b> leave requests</button><button onClick={()=>act("6 overtime claims shown")}><b>6</b> OT claims</button><button onClick={()=>act("2 contracts shown")}><b>2</b> contracts</button></div></header><div className="dark-table-wrap"><table className="os-table"><thead><tr><th>EMPLOYEE</th><th>DEPARTMENT</th><th>MANAGER</th><th>TODAY</th><th>PAYROLL</th><th>ACCESS</th></tr></thead><tbody>{people.map(p=><tr key={p[0]}><td><b>{p[1]}</b><small>{p[0]}</small></td><td>{p[2]}</td><td>{p[3]}</td><td><span className="os-dot">{p[4]}</span></td><td><span className={p[5]==="Review"?"os-pill amber":"os-pill green"}>{p[5]}</span></td><td><button onClick={()=>{setPerson(p[1]);setDrawer("profile")}}>View profile</button></td></tr>)}</tbody></table></div></section>
  {drawer==="employee"&&<ActionDrawer title="Add employee" subtitle="Create a record and begin onboarding." onClose={()=>setDrawer(null)} footer={<><button onClick={()=>setDrawer(null)}>Cancel</button><button onClick={()=>{setDrawer(null);act("Employee invitation created")}}>Create & invite</button></>}><div className="drawer-form"><FormField label="Full name"><input autoFocus placeholder="Employee name"/></FormField><FormField label="Work email"><input type="email" placeholder="name@premiercentre.com"/></FormField><FormField label="Department"><select><option>Operations</option><option>Finance</option><option>IT</option><option>Management</option></select></FormField><FormField label="Manager"><select><option>Farid Azman</option><option>Farah Ibrahim</option><option>Kumar Raj</option></select></FormField></div></ActionDrawer>}
  {drawer==="payroll"&&<ActionDrawer title="August payroll review" subtitle="PAY-0826 · RM63,400 · 128 employees" onClose={()=>setDrawer(null)} footer={<><button onClick={()=>setDrawer(null)}>Close</button><button onClick={()=>{setDrawer(null);act("Payroll sent to Accounts")}}>Approve & send to Accounts</button></>}><StepList current={3} steps={["Attendance locked","Exceptions verified","Payroll calculated","HR approval","Accounts payment"]}/><div className="drawer-callout"><b>4 resolved exceptions</b><span>Three overtime corrections and one unpaid leave adjustment are attached.</span></div></ActionDrawer>}
  {drawer==="profile"&&<ActionDrawer title={person} subtitle="Employee profile · Restricted fields protected" onClose={()=>setDrawer(null)}><div className="profile-facts"><span><small>EMPLOYEE ID</small><b>{employee?.[0]}</b></span><span><small>DEPARTMENT</small><b>{employee?.[2]}</b></span><span><small>MANAGER</small><b>{employee?.[3]}</b></span><span><small>STATUS</small><b>Active</b></span></div><div className="drawer-callout"><LockKeyhole/><span><b>Salary and banking restricted</b>Only HR and authorised payroll roles can open these records.</span></div></ActionDrawer>}
  {toast&&<div className="dark-toast">✓ {toast}</div>}
 </CloudShell>;
}
